from __future__ import annotations

from copy import deepcopy
from typing import Any

RETRIEVAL_PROFILE_SCHEMA_ID = "neo.memory.retrieval_profiles.v1"

_DEFAULT_PROFILES: dict[str, dict[str, Any]] = {
    "fast": {
        "profile_id": "fast",
        "label": "Fast keyword recall",
        "description": "SQLite keyword/FTS recall with no semantic query and no reranker.",
        "sources": ["system_records", "assistant_memory", "prompt_libraries"],
        "keyword_weight": 0.85,
        "vector_weight": 0.0,
        "recency_weight": 0.08,
        "importance_weight": 0.07,
        "rerank": False,
        "semantic": False,
        "min_score": 0.08,
        "candidate_multiplier": 2,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
    "smart": {
        "profile_id": "smart",
        "label": "Smart hybrid recall",
        "description": "Balanced keyword + optional vector recall with reranking when the Memory Engine path is ready.",
        "sources": ["system_records", "assistant_memory", "prompt_libraries"],
        "keyword_weight": 0.45,
        "vector_weight": 0.35,
        "recency_weight": 0.08,
        "importance_weight": 0.12,
        "rerank": True,
        "semantic": True,
        "min_score": 0.16,
        "candidate_multiplier": 4,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
    "deep": {
        "profile_id": "deep",
        "label": "Deep memory recall",
        "description": "Wider hybrid recall with stronger reranker usage and conservative rejection.",
        "sources": ["system_records", "assistant_memory", "prompt_libraries", "extension_manifests", "admin_config"],
        "keyword_weight": 0.35,
        "vector_weight": 0.45,
        "recency_weight": 0.06,
        "importance_weight": 0.14,
        "rerank": True,
        "semantic": True,
        "min_score": 0.18,
        "candidate_multiplier": 6,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
    "code_audit": {
        "profile_id": "code_audit",
        "label": "Code audit memory",
        "description": "Records + codebase profile for repo-aware debugging and implementation planning.",
        "sources": ["system_records", "neo_codebase", "extension_manifests", "surface_blueprints"],
        "keyword_weight": 0.42,
        "vector_weight": 0.38,
        "recency_weight": 0.04,
        "importance_weight": 0.16,
        "rerank": True,
        "semantic": True,
        "min_score": 0.15,
        "candidate_multiplier": 5,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
    "admin_diagnostic": {
        "profile_id": "admin_diagnostic",
        "label": "Admin diagnostic memory",
        "description": "Control-center retrieval for Admin config, system records, extensions, and surface ownership.",
        "sources": ["system_records", "neo_codebase", "admin_config", "surface_blueprints", "extension_manifests"],
        "keyword_weight": 0.48,
        "vector_weight": 0.32,
        "recency_weight": 0.06,
        "importance_weight": 0.14,
        "rerank": True,
        "semantic": True,
        "min_score": 0.14,
        "candidate_multiplier": 4,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
    "assistant_project": {
        "profile_id": "assistant_project",
        "label": "Assistant project memory",
        "description": "Assistant-facing recall across Assistant Scope memory, records, prompt libraries, and recent saved context. Legacy Project Workspace is retained here only for compatibility profiles.",
        "sources": ["assistant_memory", "system_records", "neo_codebase", "prompt_libraries", "admin_config", "project_workspace"],
        "keyword_weight": 0.38,
        "vector_weight": 0.38,
        "recency_weight": 0.12,
        "importance_weight": 0.12,
        "rerank": True,
        "semantic": True,
        "min_score": 0.15,
        "candidate_multiplier": 5,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
    "roleplay_runtime": {
        "profile_id": "roleplay_runtime",
        "label": "Roleplay runtime memory",
        "description": "Runtime recall for scene continuity, canon, character state, and relevant system rules.",
        "sources": ["roleplay_memory", "system_records"],
        "keyword_weight": 0.34,
        "vector_weight": 0.42,
        "recency_weight": 0.12,
        "importance_weight": 0.12,
        "rerank": True,
        "semantic": True,
        "min_score": 0.17,
        "candidate_multiplier": 5,
        "low_confidence_rejection": True,
        "include_drafts": True,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": False,
    },
    "creator_workflow": {
        "profile_id": "creator_workflow",
        "label": "Creator workflow memory",
        "description": "Recall for reusable creator workflows, prompt/caption libraries, outputs metadata, and system rules. Legacy Project Workspace remains available for Admin delivery compatibility.",
        "sources": ["assistant_memory", "prompt_libraries", "system_records", "project_workspace"],
        "keyword_weight": 0.4,
        "vector_weight": 0.35,
        "recency_weight": 0.12,
        "importance_weight": 0.13,
        "rerank": True,
        "semantic": True,
        "min_score": 0.14,
        "candidate_multiplier": 4,
        "low_confidence_rejection": True,
        "include_drafts": False,
        "include_deprecated": False,
        "include_conflicts": False,
        "require_approved": True,
    },
}


def list_retrieval_profiles() -> list[dict[str, Any]]:
    return [deepcopy(profile) for profile in _DEFAULT_PROFILES.values()]


def retrieval_profiles_payload() -> dict[str, Any]:
    return {
        "schema_id": RETRIEVAL_PROFILE_SCHEMA_ID,
        "status": "ready",
        "profiles": list_retrieval_profiles(),
        "default_profile_id": "smart",
        "policy": "Profiles are owned by the Memory Engine. Surfaces request profiles; tabs do not own embedding/reranker paths.",
    }


def get_retrieval_profile(profile_id: str | None) -> dict[str, Any]:
    key = str(profile_id or "smart").strip() or "smart"
    return deepcopy(_DEFAULT_PROFILES.get(key) or _DEFAULT_PROFILES["smart"])
