from __future__ import annotations

VOICE_BACKEND_CONTRACT_ENDPOINTS = [
    "GET /api/voice/base-contract",
    "POST /api/voice/base-contract/validate",
    "GET /api/voice/provider-routing",
    "POST /api/voice/generate",
    "GET /api/voice/generation/jobs",
    "GET /api/voice/generation/jobs/{job_id}",
    "GET /api/voice/results",
    "GET /api/voice/results/{job_id}",
    "GET /api/voice/results/{job_id}/replay",
    "GET /api/voice/results/{job_id}/download",
    "POST /api/voice/results/{job_id}/open-folder",
    "POST /api/voice/references/upload",
    "GET /api/voice/references",
    "GET /api/voice/references/{reference_id}",
    "POST /api/voice/references/{reference_id}/analyze",
    "POST /api/voice/references/{reference_id}/attest",
    "POST /api/voice/clone/generate",
    "GET /api/voice/clone/jobs/{job_id}",
    "GET /api/voice/health",
    "GET /api/voice/capabilities",
    "GET /api/voice/models",
    "GET /api/voice/voices",
    "POST /api/voice/preview",
    "POST /api/voice/render",
    "POST /api/voice/reference/upload",
    "POST /api/voice/reference/analyze",
    "GET /api/voice/reference/history",
    "GET /api/voice/jobs/{job_id}",
    "POST /api/voice/jobs/{job_id}/cancel",
    "POST /api/voice/jobs/{job_id}/retry_chunk",
    "GET /api/voice/history",
    "GET /api/voice/output-file",
]
