from __future__ import annotations

from .output_paths import output_path_payload

VOICE_SUBTABS = [
    {"subtab_id": "workspace", "display_name": "Workspace", "description": "Voice setup, backend readiness, and output folders.", "slots": ["voice.workspace.backend", "voice.workspace.summary", "voice.workspace.outputs"]},
    {"subtab_id": "generation", "display_name": "Generation", "description": "Script, voice source, delivery controls, and preview/render preparation.", "slots": ["voice.generation.script", "voice.generation.source", "voice.generation.parameters"]},
    {"subtab_id": "voice_source", "display_name": "Voice Source", "description": "Built-in voice, saved profile, and reference clone selection.", "slots": ["voice.source.builtin", "voice.source.profile", "voice.source.reference"]},
    {"subtab_id": "reference", "display_name": "Reference", "description": "Reference audio staging, QC, and zero-shot clone preparation.", "slots": ["voice.reference.upload", "voice.reference.qc", "voice.reference.notes"]},
    {"subtab_id": "finish", "display_name": "Finish", "description": "Normalize, trim, cleanup, and export lanes for completed voice output.", "slots": ["voice.finish.normalize", "voice.finish.export", "voice.finish.history"]},
    {"subtab_id": "results", "display_name": "Results", "description": "Voice output history, replay metadata, and memory export.", "slots": ["voice.results.ledger", "voice.results.replay"]},
]

VOICE_MODEL_FAMILIES = [
    {"id": "chatterbox_turbo", "label": "Chatterbox Turbo", "status": "primary_active_contract", "tier": "low_mid_vram"},
    {"id": "chatterbox_multilingual", "label": "Chatterbox Multilingual", "status": "planned", "tier": "mid_vram"},
    {"id": "kokoro_preview", "label": "Kokoro Preview", "status": "active_low_end_adapter", "tier": "low_vram", "badge": "Low-VRAM / Lightweight"},
    {"id": "fish_hq", "label": "Fish Speech HQ", "status": "active_hq_adapter", "tier": "high_vram_hq", "badge": "HQ / Advanced"},
    {"id": "custom_tts", "label": "Custom TTS", "status": "adapter_slot", "tier": "manual"},
]

VOICE_JOB_TYPES = [
    {"id": "quick_preview", "label": "Quick Preview", "status": "adapter_contract"},
    {"id": "generate_speech", "label": "Generate Speech", "status": "adapter_contract"},
    {"id": "clone_voice", "label": "Clone Voice", "status": "active"},
    {"id": "batch_script", "label": "Batch Script", "status": "active"},
    {"id": "dialogue", "label": "Dialogue / Multi-speaker", "status": "active"},
]


def voice_surface_contract_payload(*, create_paths: bool = False) -> dict:
    return {
        "schema_version": "neo.voice.surface_contract.v12",
        "surface": "voice",
        "status": "active_dialogue_multispeaker_lane",
        "current_extension_status": "active_batch_script_import_lane",
        "runtime_phase": "VO-V12",
        "current_extension_phase": "VO-V13",
        "latest_extension_phase": "VO-V14",
        "latest_extension_status": "active_voice_finish_tools_lane",
        "memory_extension_phase": "VO-V15",
        "memory_extension_status": "active_replay_metadata_memory_lane",
        "project_extension_phase": "VO-V16",
        "project_extension_status": "backend_only_compatibility",
        "subtabs": VOICE_SUBTABS,
        "model_families": VOICE_MODEL_FAMILIES,
        "job_types": VOICE_JOB_TYPES,
        "backend_ladder": ["Chatterbox", "Kokoro", "Fish Speech", "Custom TTS"],
        "output_paths": output_path_payload(create=create_paths),
        "adapter_contract": {
            "schema_id": "neo.voice.adapter_contract.v12",
            "primary_backend": "chatterbox",
            "low_end_backend": "kokoro",
            "hq_backend": "fish_speech",
            "endpoints": [
                "GET /api/voice/health",
                "GET /api/voice/capabilities",
                "GET /api/voice/capability-controls",
                "GET /api/voice/models",
                "GET /api/voice/voices",
                "POST /api/voice/preview",
                "POST /api/voice/render",
                "POST /api/voice/clone",
                "POST /api/voice/dialogue",
                "POST /api/voice/reference/upload",
                "POST /api/voice/reference/analyze",
                "GET /api/voice/reference/history",
                "GET /api/voice/profiles",
                "POST /api/voice/profiles",
                "GET /api/voice/profiles/{profile_id}",
                "PATCH /api/voice/profiles/{profile_id}",
                "DELETE /api/voice/profiles/{profile_id}",
                "GET /api/voice/jobs/{job_id}",
                "GET /api/voice/jobs/{job_id}/replay",
                "GET /api/voice/replays",
                "GET /api/voice/memory-events",
                "GET /api/voice/jobs/{job_id}/project-handoff",
                "POST /api/voice/jobs/{job_id}/project-handoff",
                "GET /api/voice/project-asset-tray",
                "GET /api/voice/queue",
                "POST /api/voice/jobs/{job_id}/cancel",
                "POST /api/voice/jobs/{job_id}/retry",
                "POST /api/voice/jobs/{job_id}/retry_chunk",
                "POST /api/voice/jobs/{job_id}/export",
                "GET /api/voice/jobs/{job_id}/reuse-settings",
                "GET /api/voice/jobs/{job_id}/open-folder",
                "DELETE /api/voice/jobs/{job_id}",
                "GET /api/voice/history",
                "GET /api/voice/exports",
                "POST /api/voice/finish",
                "POST /api/voice/finish/split",
                "POST /api/voice/finish/merge",
                "GET /api/voice/finish/history",
                "POST /api/voice/batch/import",
                "GET /api/voice/batch/history",
                "GET /api/voice/batch/{batch_id}",
                "POST /api/voice/batch/{batch_id}/render",
                "POST /api/voice/batch/{batch_id}/retry-item",
                "GET /api/voice/output-file"
            ],
            "ui_rule": "Backend card owns connection; Workspace owns preview/render intent; runtime workspace collects script, source, delivery controls, preview state, and capability-aware parameters."
        },

        "runtime_workspace": {
            "schema_id": "neo.voice.runtime_workspace.v12",
            "sections": ["script", "voice_source", "reference_clone", "saved_profiles", "delivery_controls", "capability_controls", "preview_queue_outputs", "job_queue", "history", "recovery", "export", "parameters", "chunk_plan", "hq_backend_controls", "dialogue_speaker_blocks", "speaker_mapping", "dialogue_turn_outputs", "batch_import", "batch_queue", "batch_history", "finish_tools", "finish_history"],
            "default_controls": ["script", "language", "voice source", "speaking rate", "expression", "preview", "render"],
            "advanced_controls": ["expression strength", "reference strength", "seed", "pause handling", "artifact cleanup", "backend-native extras", "split long text", "punctuation cleanup", "output format", "export wav", "export mp3", "retry failed chunk", "reuse settings", "speaker blocks", "speaker mapping", "script import", "batch queue", "output naming", "normalize", "silence trim", "noise cleanup", "loudness target", "convert wav/mp3", "split chunks", "merge chunks"],
            "preview_rule": "Preview becomes stale when script, voice source, or delivery parameters change. Quick Preview writes a Neo-owned audio file and metadata sidecar.",
            "render_rule": "Full Render creates a deterministic chunk plan, per-chunk output records, a stitched final WAV reference, and render metadata.",
            "clone_rule": "Reference Clone uses a staged reference audio file, QC metadata, and the same chunked render manifest path as speech generation.",
            "profile_rule": "Saved profiles store reusable source, backend family, language, tone tags, and default parameter snapshots under neo_data/outputs/voice/profiles.",
            "capability_rule": "VO-V8 renders advanced controls from /api/voice/capabilities control_manifest only. Unsupported backend controls are hidden instead of shown as fake-disabled options.",
            "queue_rule": "VO-V9 stores every preview/render/clone job in a queue-aware history ledger with cancellable, recoverable, exportable actions.",
            "recovery_rule": "VO-V9 retries jobs and failed chunks by creating new deterministic output records instead of overwriting old files.",
            "export_rule": "VO-V9 exposes WAV/MP3 export handoff records under neo_data/outputs/voice/exports with manifests.",
            "dialogue_rule": "VO-V12 parses speaker blocks, maps each speaker to a built-in/saved/reference voice source, renders alternating turn records, and stitches one combined WAV reference.",
            "batch_rule": "VO-V13 imports TXT/MD/CSV/JSON/SRT scripts into batch manifests, creates per-item render jobs, tracks failed items, and supports item retry.",
            "finish_rule": "VO-V14 creates finish manifests for normalize, silence trim, guarded noise cleanup, loudness target, WAV/MP3 conversion, split chunks, and merge chunks.",
            "replay_memory_rule": "VO-V15 writes replay sidecars and memory event indexes so Assistant/Control Center can reuse previous Voice settings without copying audio binaries.",
            "project_handoff_rule": "VO-V16 backend routes remain available for compatibility, but Project handoff UI is not mounted in the normal Voice tab after Pass D."
        },
        "production_runtime": {
            "schema_id": "neo.voice.production_runtime.v12",
            "queue_endpoint": "GET /api/voice/queue",
            "history_endpoint": "GET /api/voice/history",
            "export_history_endpoint": "GET /api/voice/exports",
            "finish_endpoint": "POST /api/voice/finish",
            "finish_history_endpoint": "GET /api/voice/finish/history",
            "replay_endpoint": "GET /api/voice/jobs/{job_id}/replay",
            "replay_history_endpoint": "GET /api/voice/replays",
            "memory_events_endpoint": "GET /api/voice/memory-events",
            "project_handoff_preview_endpoint": "GET /api/voice/jobs/{job_id}/project-handoff",
            "project_handoff_send_endpoint": "POST /api/voice/jobs/{job_id}/project-handoff",
            "project_asset_tray_endpoint": "GET /api/voice/project-asset-tray",
            "job_actions": ["play", "open_folder", "copy_path", "reuse_settings", "retry_job", "retry_failed_chunk", "export_wav", "export_mp3", "delete", "import_batch", "render_batch", "retry_batch_item", "finish", "normalize", "silence_trim", "convert_audio", "split_chunks", "merge_chunks", "replay", "memory_export"],
            "state_model": ["queued", "running", "preview_ready", "render_ready", "clone_render_ready", "dialogue_render_ready", "batch_render_ready", "batch_render_ready_with_failures", "failed", "cancelled", "export_ready", "finish_ready", "split_ready", "merge_ready"],
            "output_policy": "Exports, recovery manifests, replay sidecars, memory event indexes, and history records stay inside neo_data/outputs/voice; no Voice phase docs are stored in the repo root."
        },

        "kokoro_adapter": {
            "schema_id": "neo.voice.kokoro_adapter.v10",
            "profile_id": "voice.kokoro",
            "provider_id": "kokoro",
            "model_family": "kokoro_preview",
            "status": "active_low_end_adapter_contract",
            "tier": "low_vram",
            "badge": "Low-VRAM / Lightweight",
            "supports": ["tts", "preview", "render", "saved_voice_profiles", "seed", "batch", "finish_tools"],
            "unsupported_hidden": ["reference_clone", "reference_audio", "reference_strength", "dialogue", "fish_hq_controls"],
            "voices_endpoint": "GET /api/voice/voices?profile_id=voice.kokoro",
            "models_endpoint": "GET /api/voice/models?profile_id=voice.kokoro",
            "ui_rule": "When Kokoro is selected, show lightweight preview/render controls only and hide all clone/reference controls.",
        },

        "fish_speech_adapter": {
            "schema_id": "neo.voice.fish_speech_adapter.v11",
            "profile_id": "voice.fish_speech",
            "provider_id": "fish_speech",
            "model_family": "fish_hq",
            "status": "active_hq_adapter_contract",
            "tier": "high_vram_hq",
            "badge": "HQ / Advanced",
            "supports": ["tts", "preview", "render", "reference_clone", "reference_audio", "multilingual", "saved_voice_profiles", "emotion", "seed", "tags", "prosody", "pause_handling", "artifact_cleanup", "backend_native_extras", "batch", "finish_tools"],
            "guarded_until_configured": True,
            "setup_warnings": ["heavier_backend", "higher_vram_expected", "slower_startup", "advanced_setup"],
            "dialogue_policy": "VO-V12 activates dialogue through Neo speaker blocks and speaker-to-profile mapping. Fish stays guarded until a local backend is configured.",
            "voices_endpoint": "GET /api/voice/voices?profile_id=voice.fish_speech",
            "models_endpoint": "GET /api/voice/models?profile_id=voice.fish_speech",
            "ui_rule": "When Fish Speech HQ is selected, expose clone/prosody/tag/backend-native controls through the capability manifest and show HQ setup warnings.",
        },

        "dialogue_lane": {
            "schema_id": "neo.voice.dialogue_lane.v12",
            "status": "active",
            "endpoint": "POST /api/voice/dialogue",
            "script_formats": ["[Speaker] blocks", "Speaker: line"],
            "speaker_sources": ["built_in", "saved_profile", "reference_clone"],
            "outputs": ["dialogue_plan", "speaker_manifest", "turn_outputs", "combined_wav", "dialogue_metadata"],
            "non_goals": ["No SRT alignment", "No finish/mastering DSP", "No training or dataset builder"],
            "ui_rule": "Dialogue UI shows speaker blocks and speaker mapping only when supports_dialogue is true. Kokoro keeps this lane hidden."
        },

        "batch_import_lane": {
            "schema_id": "neo.voice.batch_import_lane.v13",
            "status": "active",
            "import_endpoint": "POST /api/voice/batch/import",
            "history_endpoint": "GET /api/voice/batch/history",
            "render_endpoint": "POST /api/voice/batch/{batch_id}/render",
            "retry_item_endpoint": "POST /api/voice/batch/{batch_id}/retry-item",
            "import_types": ["txt", "md", "csv", "json", "srt"],
            "outputs": ["batch_manifest", "batch_history_index", "per_item_voice_jobs", "failed_item_retry_records"],
            "output_folder": "neo_data/outputs/voice/batch/",
            "ui_rule": "Batch Import appears when supports_batch is true. Imported items create normal preview/render/dialogue jobs so queue/history/export stay unified."
        },

        "finish_tools_lane": {
            "schema_id": "neo.voice.finish_tools_lane.v14",
            "status": "active",
            "finish_endpoint": "POST /api/voice/finish",
            "split_endpoint": "POST /api/voice/finish/split",
            "merge_endpoint": "POST /api/voice/finish/merge",
            "history_endpoint": "GET /api/voice/finish/history",
            "tools": ["normalize", "silence_trim", "noise_cleanup", "loudness_target", "convert_wav_mp3", "split_chunks", "merge_chunks"],
            "output_folder": "neo_data/outputs/voice/finish/",
            "export_folder": "neo_data/outputs/voice/exports/",
            "ui_rule": "Finish Tools operate on completed Voice outputs and write manifest-first records. Encoder/DSP internals can be upgraded later without changing the route contract.",
            "non_goals": ["No VO-V16 project handoff", "No training/dataset tools"]
        },

        "replay_memory_lane": {
            "schema_id": "neo.voice.replay_memory_lane.v15",
            "status": "active",
            "job_replay_endpoint": "GET /api/voice/jobs/{job_id}/replay",
            "replay_history_endpoint": "GET /api/voice/replays",
            "memory_events_endpoint": "GET /api/voice/memory-events",
            "project_handoff_preview_endpoint": "GET /api/voice/jobs/{job_id}/project-handoff",
            "project_handoff_send_endpoint": "POST /api/voice/jobs/{job_id}/project-handoff",
            "project_asset_tray_endpoint": "GET /api/voice/project-asset-tray",
            "replay_sidecar_pattern": "neo_data/outputs/voice/metadata/<job_id>.replay.v15.json",
            "memory_event_index": "neo_data/outputs/voice/history/voice_memory_events.v15.json",
            "exports": ["voice_job_event", "script_fragment", "voice_profile_fact", "backend_settings_object", "output_file_object"],
            "assistant_reuse_rule": "Assistant can reuse voice source, backend family/runtime, model, parameters, speaker manifest, and script context from a previous Voice job.",
            "non_goals": ["No binary copy", "No Project asset tray handoff", "No timeline link"]
        },

        "project_handoff_lane": {
            "schema_id": "neo.voice.project_handoff_lane.v16",
            "status": "backend_only_compatibility",
            "preview_endpoint": "GET /api/voice/jobs/{job_id}/project-handoff",
            "send_endpoint": "POST /api/voice/jobs/{job_id}/project-handoff",
            "asset_tray_endpoint": "GET /api/voice/project-asset-tray",
            "resource_type": "voice_output",
            "handoff_policy": "Store output path, replay metadata path, memory event id, speaker manifest, and context summary only. Do not copy WAV/MP3 binaries into Project Workspace.",
            "outputs": ["project_link", "project_handoff", "project_timeline_event", "voice_filtered_asset_tray"],
            "ui_rule": "Do not render Project handoff controls in the normal Voice tab after Pass D; Assistant/Admin may call backend routes explicitly later."
        },

        "capability_ui": {
            "schema_id": "neo.voice.capability_ui.v8",
            "source_endpoint": "GET /api/voice/capabilities",
            "control_manifest_key": "control_manifest",
            "support_flags": ["supports_cloning", "supports_multilingual", "supports_emotion", "supports_seed", "supports_tags", "supports_dialogue", "supports_speaker_mapping", "supports_batch", "supports_finish_tools", "supports_audio_convert", "supports_split_merge", "supports_replay_metadata", "supports_memory_export"],
            "zones": ["default", "advanced", "backend_native"],
            "source_visibility_rule": "Built-in voice is always available. Saved Profile appears when saved profile support exists. Reference Clone appears only when cloning and reference audio are both supported.",
            "backend_switch_rule": "Changing runtime/model family refreshes the capability manifest and re-renders only visible/enabled controls.",
        },
        "runtime_lanes": [
            {"id": "quick_preview", "label": "Quick Preview", "status": "adapter_contract_ready", "requires_backend": "chatterbox"},
            {"id": "generate_speech", "label": "Generate Speech", "status": "chunked_render_ready", "requires_backend": "chatterbox", "outputs": ["chunks", "final_wav", "render_metadata"]},
            {"id": "clone_voice", "label": "Clone Voice", "status": "reference_lane_ready", "requires_backend": "clone_capability", "outputs": ["reference_audio", "reference_qc", "clone_render_manifest"]},
            {"id": "dialogue", "label": "Dialogue / Multi-speaker", "status": "active_dialogue_lane", "requires_backend": "dialogue_capability", "outputs": ["dialogue_plan", "speaker_manifest", "turn_outputs", "combined_wav", "dialogue_metadata"]},
            {"id": "batch_script", "label": "Batch + Script Import", "status": "active_batch_import_lane", "requires_backend": "render_capability", "outputs": ["batch_manifest", "batch_history", "per_item_jobs", "failed_item_retry"]},
            {"id": "finish_tools", "label": "Voice Finish Tools", "status": "active_finish_tools_lane", "requires_backend": "completed_output", "outputs": ["finish_manifest", "finished_audio", "split_parts", "merged_wav", "finish_history"]},
            {"id": "replay_memory", "label": "Replay Metadata + Memory", "status": "active_replay_memory_lane", "requires_backend": "completed_output", "outputs": ["replay_sidecar", "memory_event", "reuse_payload"]},
        ],
        "voice_sources": [
            {"id": "built_in", "label": "Built-in Voice", "status": "active_shell"},
            {"id": "saved_profile", "label": "Saved Profile", "status": "active_profile_store", "outputs": ["profile_sidecar", "profile_index"]},
            {"id": "reference_clone", "label": "Reference Clone", "status": "active_reference_upload_qc"},
        ],
        "built_in_panels": [
            {"id": "script", "label": "Script", "subtabs": ["generation", "workspace"]},
            {"id": "voice_source", "label": "Voice Source", "subtabs": ["generation", "voice_source", "reference"]},
            {"id": "delivery", "label": "Delivery Controls", "subtabs": ["generation"]},
            {"id": "preview_results", "label": "Preview / Results", "subtabs": ["generation", "results"]},
            {"id": "replay_memory", "label": "Replay / Memory", "subtabs": ["results"]},
            {"id": "batch_import", "label": "Batch Import", "subtabs": ["generation", "results"]},
            {"id": "finish", "label": "Finish Tools", "subtabs": ["finish"]},
        ],
        "non_goals": [
            "VO-V7 keeps reference audio upload/QC active and adds saved voice profiles for reusable built-in or reference-clone settings. Actual audio quality still depends on the configured backend.",
            "Training/dataset builder and multi-speaker rendering remain out of scope for VO-V7.",
            "Voice UI talks to Neo /api/voice/* routes only, never directly to raw backend APIs.",
            "VO-V8 does not add new synthesis backends; Kokoro/Fish remain later adapter phases after the capability UI contract is stable.",
            "VO-V9 does not implement finish/mastering DSP; normalize/trim flags are export metadata handoffs until VO-V14 Finish Tools.",
            "VO-V10 activates Kokoro as a low-end backend adapter contract only. It adds model/voice/capability routing, but does not add Fish, dialogue, batch, or finish DSP.",
            "VO-V11 activates Fish Speech HQ as a guarded advanced adapter contract. It adds HQ model/voice/capability routing and warnings, but does not add VO-V13 batch import or VO-V14 finish DSP.",
            "VO-V12 activates dialogue/multi-speaker manifests, but does not add batch import, SRT alignment, or finish/mastering DSP.",
            "VO-V13 activates batch/script import for TXT, Markdown, CSV, JSON, and SRT. It does not add finish/mastering DSP or project handoff.",
            "VO-V14 activates Voice Finish Tools for manifest-first normalize, trim, cleanup, conversion, split, and merge.",
            "VO-V15 activates replay metadata and memory event exports.",
            "VO-V16 backend handoff routes remain compatibility-only after Pass D; normal Voice tab Project UI is not mounted.",
        ],
    }
